// Formula cards: formula + step-by-step procedure + the mistake to avoid at each step.
// Notation follows Briggs/Cochran Calculus (6.1-6.5, 6.7) and the class notes.
window.CARDS = [
  {
    id: 'motion', sec: '6.1', title: 'Position from velocity (and velocity from acceleration)', types: ['pos-v', 'pos-a'],
    formula: '$$s(t) = s(0) + \\int_0^t v(x)\\,dx \\qquad v(t) = v(0) + \\int_0^t a(x)\\,dx$$',
    when: 'Given \\(v(t)\\) (or \\(a(t)\\)) and a starting value; asked for position at a time or the position function.',
    steps: [
      ['Write what you are given: \\(v(t)\\) or \\(a(t)\\), \\(s(0)\\), \\(v(0)\\).', 'Mixing up \\(v(0)\\) and \\(s(0)\\).'],
      ['Antidifferentiate once to go \\(a \\to v\\), and again for \\(v \\to s\\).', 'Differentiating instead of integrating (position is the antiderivative of velocity).'],
      ['Find \\(C\\) by plugging in \\(t = 0\\): \\(s(0)\\) must match the given value.', 'Setting \\(C = s(0)\\) when the antiderivative is not 0 at \\(t = 0\\). Example: \\(\\int 3\\sin t\\,dt = -3\\cos t + C\\), and \\(-3\\cos 0 = -3\\), so \\(C = s(0) + 3\\).'],
      ['When going \\(a \\to v \\to s\\), integrate the whole \\(v(t)\\), including the \\(v(0)\\) term (it becomes \\(v(0)\\,t\\)).', 'Dropping \\(v(0)\\,t\\).'],
      ['Plug in the time asked for.', 'Reporting the displacement \\(s(T) - s(0)\\) instead of the position \\(s(T)\\).'],
    ],
    check: 'Differentiate your \\(s(t)\\): you must get \\(v(t)\\) back, and \\(s(0)\\) must equal the given value. Units: meters.',
  },
  {
    id: 'distance', sec: '6.1', title: 'Displacement vs distance traveled', types: ['disp-dist'],
    formula: '$$\\text{displacement} = \\int_a^b v(t)\\,dt \\qquad \\text{distance} = \\int_a^b |v(t)|\\,dt$$',
    when: '"Displacement", "net change in position", "how far from the start" use \\(v\\). "Total distance traveled", "odometer" use \\(|v|\\).',
    steps: [
      ['Find where \\(v(t) = 0\\) inside \\((a, b)\\): factor \\(v\\).', 'Keeping roots outside the interval, or missing one.'],
      ['Displacement: integrate \\(v\\) straight from \\(a\\) to \\(b\\).', 'Splitting or taking absolute values here. Displacement keeps signs.'],
      ['Distance: split \\([a, b]\\) at every zero of \\(v\\); integrate \\(v\\) on each piece.', 'Not splitting: forward and backward motion cancel.'],
      ['Add the absolute values of the pieces.', 'Using \\(|\\text{displacement}|\\) as the distance. That still lets pieces cancel.'],
    ],
    check: 'Distance \\(\\ge\\) |displacement|, always. They are equal only if \\(v\\) never changes sign.',
  },
  {
    id: 'area-x', sec: '6.2', title: 'Area between curves (integrate dx)', types: ['area-x'],
    formula: '$$A = \\int_a^b \\big(f(x) - g(x)\\big)\\,dx,\\qquad f = \\text{top},\\ g = \\text{bottom}$$',
    when: 'Curves given as \\(y = \\dots\\) and the same curve is on top across the whole region.',
    steps: [
      ['Sketch (Desmos). Find intersections: set the curves equal and solve.', 'Using bounds from the problem when the curves actually meet earlier.'],
      ['Decide top and bottom: test a point between the bounds.', 'Guessing; the "bigger looking" formula is not always on top.'],
      ['Integrand = top − bottom. Expand.', 'Bottom − top (negative area) or forgetting to subtract the bottom.'],
      ['Antidifferentiate term by term.', 'Off-by-factor: \\(x^n \\to \\frac{x^{n+1}}{n+1}\\).'],
      ['Evaluate \\(F(b) - F(a)\\).', 'Forgetting \\(F(a)\\) when \\(a \\ne 0\\); sign slips with negative bounds (use parentheses).'],
    ],
    check: 'Area must be positive. If negative, top and bottom are swapped.',
  },
  {
    id: 'area-y', sec: '6.2', title: 'Area between curves (integrate dy)', types: ['area-y'],
    formula: '$$A = \\int_c^d \\big(f(y) - g(y)\\big)\\,dy,\\qquad f = \\text{right},\\ g = \\text{left}$$',
    when: 'Curves given as \\(x = \\dots\\), or doing it in \\(dx\\) would need a split.',
    steps: [
      ['Write every curve as \\(x = (\\text{function of } y)\\).', 'Leaving an \\(x\\) in the integrand.'],
      ['Find the \\(y\\)-values where the curves meet.', 'Using \\(x\\)-values as bounds.'],
      ['Integrand = right − left.', 'Top − bottom thinking here. In \\(dy\\) it is right − left.'],
      ['Antidifferentiate in \\(y\\), evaluate \\(F(d) - F(c)\\).', 'Sign slips with negative bounds.'],
    ],
    check: 'Positive answer; spot-check a horizontal line: right curve has the larger \\(x\\).',
  },
  {
    id: 'area-split', sec: '6.2', title: 'Area when the curves cross (split the region)', types: ['area-split'],
    formula: '$$A = \\int_a^b |f(x) - g(x)|\\,dx = \\int_a^c (f - g)\\,dx + \\int_c^b (g - f)\\,dx$$',
    when: 'Interval is given and the curves cross inside it, or a boundary changes formula partway (then consider \\(dy\\)).',
    steps: [
      ['Solve \\(f = g\\); keep crossings inside the interval.', 'Not checking for a crossing at all.'],
      ['On each piece, decide which curve is on top (test point).', 'Assuming the same curve stays on top.'],
      ['Integrate top − bottom on each piece.', 'One integral straight across: pieces cancel.'],
      ['Add the (positive) pieces.', 'Taking |net integral|.'],
    ],
    check: 'Each piece positive. Total \\(\\ge\\) |net integral|.',
  },
  {
    id: 'washer', sec: '6.3', title: 'Disk / washer method', types: ['washer-x', 'washer-h', 'washer-y', 'washer-v'],
    formula: '$$V = \\pi\\int_a^b \\big(R^2 - r^2\\big)\\,dx \\quad(\\text{disk: } r = 0)$$ Slices are <b>perpendicular</b> to the axis. Axis horizontal → \\(dx\\). Axis vertical → \\(dy\\) (write curves as \\(x = g(y)\\)).',
    when: 'The curve is easy in the variable along the axis; often the easy choice about the \\(x\\)-axis.',
    steps: [
      ['Sketch region and axis. Draw one slice perpendicular to the axis.', 'Drawing the slice parallel (that is a shell).'],
      ['Pick the variable: along the axis (\\(dx\\) for horizontal axis, \\(dy\\) for vertical).', 'Integrating \\(dx\\) about the \\(y\\)-axis with washers.'],
      ['Bounds: intersections in that variable.', 'Using \\(x\\)-values when integrating \\(dy\\).'],
      ['\\(R\\) = distance from axis to the <b>farther</b> boundary; \\(r\\) = distance to the <b>closer</b> one (0 if the region touches the axis: disk).', 'Swapping \\(R\\) and \\(r\\); forgetting the hole.'],
      ['Axis \\(y = k\\): radius = \\(|\\text{curve} - k|\\). Below the region: curve − k. Above: k − curve.', 'Measuring from the \\(x\\)-axis anyway; \\(f - (-2)\\) is \\(f + 2\\), not \\(f - 2\\).'],
      ['Integrand \\(R^2 - r^2\\). Expand.', '\\((R - r)^2\\) is wrong. Square each separately.'],
      ['Antidifferentiate, evaluate \\(F(b) - F(a)\\), multiply by \\(\\pi\\).', 'Dropping the \\(\\pi\\), or using \\(2\\pi\\) (that is shells).'],
    ],
    check: 'Volume positive. Units cubed. Washer and shell must give the same number for the same solid.',
  },
  {
    id: 'slice', sec: '6.3', title: 'General slicing (known cross-sections)', types: ['slice'],
    formula: '$$V = \int_a^b A(x)\,dx$$ Square: \(A = s^2\). Semicircle on diameter \(s\): \(A = \tfrac{\pi}{8}s^2\). Isosceles right triangle on a leg \(s\): \(A = \tfrac12 s^2\). Equilateral triangle: \(A = \tfrac{\sqrt3}{4}s^2\).',
    when: 'A base region is given and the cross-sections perpendicular to an axis are squares, semicircles, triangles. Nothing is revolved.',
    steps: [
      ['Sketch the base. Slices perpendicular to the \(x\)-axis → \(dx\); perpendicular to the \(y\)-axis → \(dy\) (write curves as \(x = g(y)\)).', 'Using the wrong variable for the slice direction.'],
      ['Bounds: the extent of the base in that variable.', 'Using \(x\)-values when integrating \(dy\).'],
      ['Slice length \(s\) = top − bottom (or right − left).', 'Using just the top curve.'],
      ['Area \(A\) from the shape formula in terms of \(s\).', 'Semicircle: \(s\) is the diameter, so \(r = s/2\) and \(A = \tfrac12\pi(s/2)^2 = \tfrac{\pi}{8}s^2\), not \(\pi s^2\).'],
      ['Integrate \(A\) over the bounds. No \(\pi\) unless the shape is circular.', 'Adding \(\pi\) out of washer habit.'],
    ],
    check: 'Squares beat triangles (½) beat semicircles (π/8 ≈ 0.39) for the same base. Units cubed.',
  },
  {
    id: 'shell', sec: '6.4', title: 'Shell method', types: ['shell-y', 'shell-v', 'shell-x', 'shell-h'],
    formula: '$$V = 2\\pi\\int_a^b (\\text{radius})(\\text{height})\\,dx$$ Shells are <b>parallel</b> to the axis. Axis vertical → \\(dx\\). Axis horizontal → \\(dy\\) (write curves as \\(x = g(y)\\)).',
    when: 'Washers would need solving for the other variable, or splitting; or the bound is 0 and the product is clean.',
    steps: [
      ['Sketch; draw one shell parallel to the axis.', 'Drawing it perpendicular (that is a washer).'],
      ['Variable: opposite to the axis (\\(dx\\) about a vertical axis, \\(dy\\) about a horizontal axis).', 'Shells about the \\(x\\)-axis in \\(dx\\).'],
      ['Bounds in that variable.', 'Using the other variable\'s values.'],
      ['Radius = distance from the axis to the shell. About \\(x = k\\): \\(x - k\\) if the axis is left of the region, \\(k - x\\) if right.', 'Using plain \\(x\\) when the axis is \\(x = k\\); sign slip in \\(x - (-2) = x + 2\\).'],
      ['Height = top − bottom (in \\(dy\\): right − left). The axis never changes the height.', 'Forgetting to subtract the bottom/left curve.'],
      ['Integrand = radius × height. Expand.', 'Squaring something (nothing is squared in shells).'],
      ['Antidifferentiate, evaluate, multiply by \\(2\\pi\\).', 'Using \\(\\pi\\) instead of \\(2\\pi\\).'],
    ],
    check: 'Positive volume. Compare with the washer setup if both are possible.',
  },
  {
    id: 'both', sec: '6.4', title: 'Set up both ways, evaluate the easier', types: ['both'],
    formula: 'Washer: \\(\\pi\\int (R^2 - r^2)\\) along the axis. Shell: \\(2\\pi\\int(\\text{radius})(\\text{height})\\) across the axis.',
    when: 'Class format: set up both integrals, then evaluate only the easier one.',
    steps: [
      ['Washer: variable along the axis, bounds, \\(R\\), \\(r\\).', 'Mixing pieces: washers need \\(R, r\\); shells need radius, height. Don\'t mix.'],
      ['Shell: variable across the axis, solve curves for that variable, bounds, radius, height.', 'Forgetting to convert bounds to the new variable.'],
      ['Pick the easier one: bound at 0, no squares of messy expressions, no solving for \\(x\\).', 'Grinding the messy one.'],
      ['Evaluate it.', 'Different answers from the two setups means one setup is wrong.'],
    ],
    check: 'Both integrals must give the same number (same solid).',
  },
  {
    id: 'arc', sec: '6.5', title: 'Arc length', types: ['arc-x', 'arc-y', 'arc-setup'],
    formula: '$$L = \\int_a^b \\sqrt{1 + f\'(x)^2}\\,dx \\qquad L = \\int_c^d \\sqrt{1 + g\'(y)^2}\\,dy$$ Requires \\(f\'\\) continuous on \\([a, b]\\).',
    when: '"Length of the curve". Odometer reading along the curve, not the straight-line distance.',
    steps: [
      ['Differentiate: \\(f\'(x)\\).', 'Power rule slips, e.g. \\(\\tfrac{4\\sqrt2}{3}x^{3/2} \\to 2\\sqrt2\\,x^{1/2}\\); constants vanish.'],
      ['Square it: \\((f\')^2\\). Then add 1.', 'Forgetting to square, or forgetting the 1. \\((2\\sqrt2)^2 = 8\\).'],
      ['Simplify \\(1 + (f\')^2\\): look for a perfect square \\((P + N)^2\\) when \\(f\' = P - N\\) with \\(4PN = 1\\).', 'Taking \\(\\sqrt{(P+N)^2}\\) as \\(P - N\\).'],
      ['If it is \\(\\sqrt{1 + mx}\\): \\(u = 1 + mx\\), \\(du = m\\,dx\\), change the bounds to \\(u\\)-values.', 'Dropping the \\(1/m\\); forgetting to change bounds.'],
      ['Evaluate; leave exact form unless asked for a decimal.', 'Rounding early.'],
    ],
    check: 'L \\(\\ge\\) straight-line distance between the endpoints. For a line, L equals the distance formula.',
  },
  {
    id: 'spring', sec: '6.7', title: 'Work: springs (Hooke\'s law)', types: ['spring'],
    formula: '$$F(x) = kx,\\qquad W = \\int_a^b kx\\,dx = \\frac{k}{2}\\left(b^2 - a^2\\right)$$ \\(x\\) = distance stretched (or compressed) <b>beyond natural length</b>, in meters.',
    when: 'Spring, stretch, compress, natural length.',
    steps: [
      ['Convert all lengths to meters.', 'Working in cm: k comes out 100× too small.'],
      ['Find \\(k\\) from the given force: \\(k = F/x\\). If given work instead: \\(W = kd^2/2\\), so \\(k = 2W/d^2\\).', 'Using the total length instead of the stretch.'],
      ['Bounds: start and end stretch beyond natural length.', '"Additional 0.2 m" starts at the current stretch, not 0.'],
      ['\\(W = \\frac{k}{2}(b^2 - a^2)\\).', 'Forgetting the \\(\\tfrac12\\); writing \\((b - a)^2\\).'],
    ],
    check: 'Units: N/m for k, joules for W.',
  },
  {
    id: 'chain', sec: '6.7', title: 'Work: lifting chains and ropes', types: ['chain'],
    formula: '$$W = \\int_0^L (\\rho g)\\,y\\,dy = \\frac{\\rho g L^2}{2}$$ \\(y\\) = distance of a slice below the top, \\(\\rho g\\) = weight per length.',
    when: 'Chain/rope/cable hanging and being wound up. Each piece rises a different distance.',
    steps: [
      ['Weight per length: \\(\\rho g\\) (metric, \\(g = 9.8\\)). US units in lb/ft are already a weight.', 'Using kg/m as if it were a weight.'],
      ['Slice at depth \\(y\\): weight \\(\\rho g\\,dy\\), lifted \\(y\\).', 'Lifting distance \\(L - y\\) when \\(y\\) is measured from the top.'],
      ['Only part wound up? Top part: \\(\\int_0^{h}\\rho g\\,y\\,dy\\). The rest rises \\(h\\) as a block: (its weight)\\((h)\\).', 'Ignoring the part that rises as a block.'],
      ['A load at the end: add (load weight)(distance), no integral.', 'Integrating the load.'],
    ],
    check: 'Units: joules (N·m) or ft·lb.',
  },
  {
    id: 'pump', sec: '6.7', title: 'Work: pumping liquids', types: ['pump'],
    formula: '$$W = \\int_{\\text{bottom of liquid}}^{\\text{top of liquid}} \\rho g\\,A(y)\\,D(y)\\,dy$$ \\(A(y)\\) = area of the horizontal slice at height \\(y\\); \\(D(y)\\) = distance that slice is lifted. Water: \\(\\rho g = 9800\\ \\text{N/m}^3\\) (or 62.5 lb/ft³ if given).',
    when: 'Tank, pump, water out over the top or to an outlet.',
    steps: [
      ['Set \\(y = 0\\) at the bottom of the tank, \\(y\\) up.', 'Mixing two coordinate systems.'],
      ['Slice area \\(A(y)\\): cylinder \\(\\pi r^2\\); box \\(lw\\); cone/trough: similar triangles give the radius/width at height \\(y\\); hemisphere \\(\\pi(R^2 - (R - y)^2)\\).', 'Using the top radius for every slice of a cone.'],
      ['Lift distance \\(D(y)\\) = (destination height) − \\(y\\). Outlet \\(h\\) above a tank of height \\(H\\): \\(H + h - y\\).', 'Using \\(y\\) as the lift distance; forgetting the outlet height.'],
      ['Bounds: only where the liquid is (0 to the depth).', 'Integrating to the tank height when it is only partly full.'],
      ['Multiply by \\(\\rho g\\).', 'Using \\(\\rho = 1000\\) without \\(g\\).'],
    ],
    check: 'Units: joules. More water or a higher outlet must mean more work.',
  },
  {
    id: 'force', sec: '6.7', title: 'Force and pressure on a vertical plate', types: ['force'],
    formula: '$$F = \\int_0^{\\text{top of plate}} \\rho g\\,(\\text{depth})\\,w(y)\\,dy$$ $$\\text{depth} = a - y$$ \\(y\\) up from the bottom of the plate, water surface at \\(y = a\\). Pressure \\(p = \\rho g\\cdot\\text{depth}\\).',
    when: 'Dam, window, plate submerged vertically; force on one side.',
    steps: [
      ['Coordinates: \\(y = 0\\) at the bottom of the plate; find \\(a\\) = height of the surface.', 'Forgetting that a plate sunk below the surface has \\(a > \\) plate height.'],
      ['Width \\(w(y)\\) of a horizontal strip: constant for a rectangle; linear for triangles/trapezoids (use the side lines).', 'Using a constant width for a triangle.'],
      ['Depth of the strip = \\(a - y\\).', 'Using \\(y\\) as the depth.'],
      ['Bounds: over the plate only.', 'Integrating up to the surface.'],
      ['Multiply by \\(\\rho g\\) (9800 N/m³ for water).', 'Using \\(\\rho\\) alone.'],
    ],
    check: 'Units: newtons (or lb). Deeper plate means more force.',
  },
  {
    id: 'mass', sec: '6.7', title: 'Mass of a thin bar', types: ['mass'],
    formula: '$$m = \\int_a^b \\rho(x)\\,dx$$',
    when: 'Density varies along a bar (kg/m).',
    steps: [
      ['Integrand is the density \\(\\rho(x)\\).', 'Multiplying one density value by the length.'],
      ['Antidifferentiate, evaluate.', 'Usual power-rule slips.'],
    ],
    check: 'Mass between (min density)·length and (max density)·length.',
  },
  {
    id: 'sh-box', sec: 'Shapes', title: 'Rectangular tank / sloped pool', types: ['sh-box'],
    formula: 'Origin at the bottom, \\(y\\) up. $$A(y) = \\ell\\cdot w\\quad\\text{(the same at every height)}$$ Example: a 10 by 4 tank: \\(A(y) = 10\\times 4 = 40\\). Sloped pool, origin at the deepest point, floor rises \\(s\\) over the length \\(L\\): $$\\frac{\\ell}{y} = \\frac{L}{s}\\;\\Rightarrow\\;\\ell = \\frac{L}{s}\\,y,\\qquad A(y) = W\\cdot\\frac{L}{s}\\,y$$ Example: \\(L = 30\\), \\(s = 3\\), \\(W = 10\\): \\(\\frac{\\ell}{y} = \\frac{30}{3}\\), so \\(\\ell = 10y\\) and \\(A(y) = 10\\cdot 10y = 100y\\).',
    when: 'Box, rectangular tank, swimming pool.',
    steps: [
      ['Write what you know: length, width, height (pool: how far the floor drops, \\(s\\)).', 'Using the height as a side of the slice.'],
      ['Straight walls: the slice is the floor rectangle. Sloped floor: similar triangles give the slice length, \\(\\frac{\\ell}{y} = \\frac{L}{s}\\).', 'Using the full pool length below the shallow-end floor.'],
      ['\\(A(y) = \\text{length}\\times\\text{width}\\).', 'Adding, or multiplying by the height too (that is the volume).'],
    ],
    check: 'A box slice never depends on \\(y\\). A pool slice is 0 at the deepest point and the full \\(L\\times W\\) at the shallow floor.',
  },
  {
    id: 'sh-cyl', sec: 'Shapes', title: 'Upright cylinder', types: ['sh-cyl'],
    formula: 'Origin at the centre of the bottom, \\(y\\) up. $$A(y) = \\pi r^2\\quad\\text{(the same at every height)}$$ Example: radius 3: \\(A(y) = \\pi\\cdot 3^2 = 9\\pi\\). Diameter 6: first \\(r = \\frac{6}{2} = 3\\).',
    when: 'Upright cylindrical tank.',
    steps: [
      ['Write what you know: radius (or diameter) and height.', 'Using the diameter as the radius.'],
      ['The wall is straight up, so \\(r\\) is the same at every \\(y\\).', 'Making \\(r\\) depend on \\(y\\).'],
      ['\\(A(y) = \\pi r^2\\).', 'Writing \\(2\\pi r\\) (that is the distance around) or dropping \\(\\pi\\).'],
    ],
    check: 'Area is a constant times \\(\\pi\\).',
  },
  {
    id: 'sh-cone', sec: 'Shapes', title: 'Cone (point down or up)', types: ['sh-cone'],
    formula: 'Point down, origin at the point: $$\\frac{r}{y} = \\frac{R}{H}\\;\\Rightarrow\\; r = \\frac{R}{H}\\,y,\\qquad A(y) = \\pi\\left(\\frac{R}{H}\\,y\\right)^2$$ Example: \\(R = 3\\), \\(H = 2\\): \\(\\frac{r}{y} = \\frac{3}{2}\\), so \\(r = \\frac{3}{2}y\\) and \\(A(y) = \\pi\\cdot\\frac{9}{4}y^2\\). Point up, origin at the centre of the bottom: $$\\frac{r}{H - y} = \\frac{R}{H}\\;\\Rightarrow\\; r = \\frac{R}{H}(H - y)$$ Example: \\(R = 3\\), \\(H = 6\\): \\(r = \\frac{1}{2}(6 - y) = 3 - \\frac{1}{2}y\\).',
    when: 'Conical tank, funnel, cone of water.',
    steps: [
      ['Write what you know: \\(R\\) = radius of the wide end, \\(H\\) = height. Which way does the point face?', 'Using the diameter as \\(R\\).'],
      ['The equation it gives (similar triangles): \\(\\frac{r}{y} = \\frac{R}{H}\\) with your numbers (point up: \\(\\frac{r}{H - y}\\)).', 'Flipping the fraction: radius goes with radius.'],
      ['Solve for \\(r\\): multiply both sides by \\(y\\) (or by \\(H - y\\)).', 'Using \\(R\\) for every slice.'],
      ['\\(A(y) = \\pi r^2\\): square the whole \\(r\\), fraction included.', 'Squaring only the \\(y\\).'],
    ],
    check: 'Point down: \\(r = 0\\) at \\(y = 0\\) and \\(r = R\\) at \\(y = H\\). Point up: the other way round.',
  },
  {
    id: 'sh-hcyl', sec: 'Shapes', title: 'Cylinder lying on its side', types: ['sh-hcyl'],
    formula: 'The slice is a rectangle, \\(L\\) long and \\(2x\\) wide. Origin at the centre of an end: $$x^2 + y^2 = R^2\\;\\Rightarrow\\; x = \\sqrt{R^2 - y^2},\\qquad A(y) = 2L\\sqrt{R^2 - y^2}$$ Origin at the bottom (centre at \\(y = R\\)): $$x^2 + (y - R)^2 = R^2\\;\\Rightarrow\\; x = \\sqrt{R^2 - (y - R)^2}$$ Example: \\(R = 3\\), \\(L = 10\\), origin at the bottom: \\(x = \\sqrt{9 - (y - 3)^2}\\), \\(A(y) = 20\\sqrt{9 - (y - 3)^2}\\).',
    when: 'Tank lying on its side (oil tank, tanker truck).',
    steps: [
      ['Write what you know: \\(R\\), \\(L\\), and where the origin is. The centre of the circle is at \\(y = 0\\) or \\(y = R\\).', 'Putting the centre at \\(y = 0\\) when the origin is at the bottom.'],
      ['The equation it gives (Pythagoras): \\(x^2 + (\\text{height above the centre})^2 = R^2\\).', 'Forgetting to shift: \\(y - R\\), not \\(y\\).'],
      ['Solve for \\(x\\), the half-width; the slice is \\(2x\\) wide and \\(L\\) long.', 'Using \\(x\\) as the full width.'],
    ],
    check: 'Widest slice (\\(2R\\)) through the centre; 0 at the bottom and top.',
  },
  {
    id: 'sh-sphere', sec: 'Shapes', title: 'Sphere / hemisphere', types: ['sh-sphere'],
    formula: 'The slice is a circle of radius \\(r\\). Origin at the centre: $$r^2 + y^2 = R^2\\;\\Rightarrow\\; A(y) = \\pi(R^2 - y^2)$$ Origin at the bottom (centre at \\(y = R\\)): $$r^2 + (y - R)^2 = R^2\\;\\Rightarrow\\; A(y) = \\pi\\left(R^2 - (y - R)^2\\right) = \\pi(2Ry - y^2)$$ Example: \\(R = 5\\), origin at the bottom, \\(y = 2\\): \\(r^2 = 25 - (2 - 5)^2 = 25 - 9 = 16\\), so \\(A = 16\\pi\\). A hemisphere is the same circle, just half the \\(y\\) range.',
    when: 'Spherical tank, hemispherical bowl or dome.',
    steps: [
      ['Write what you know: \\(R\\) and where the origin is (centre or bottom).', 'Mixing the two origins.'],
      ['The equation it gives (Pythagoras): \\(r^2 + (\\text{height above the centre})^2 = R^2\\).', 'Using \\(R\\) as every slice\'s radius.'],
      ['\\(A(y) = \\pi r^2\\): squaring removes the square root.', 'Leaving a square root in \\(A(y)\\).'],
    ],
    check: 'Biggest slice \\(\\pi R^2\\) through the centre; 0 at the top and bottom of a sphere.',
  },
  {
    id: 'sh-tri', sec: 'Shapes', title: 'Trough: triangle ends (point up or down)', types: ['sh-tri'],
    formula: 'The slice is a rectangle: \\(A(y) = \\ell\\cdot w\\). Point down, origin at the point: $$\\frac{w}{y} = \\frac{b}{h}\\;\\Rightarrow\\; w = \\frac{b}{h}\\,y$$ Point up, origin at the bottom edge: $$\\frac{w}{h - y} = \\frac{b}{h}\\;\\Rightarrow\\; w = \\frac{b}{h}(h - y)$$ Example: \\(b = 4\\), \\(h = 2\\), \\(\\ell = 10\\), point down: \\(\\frac{w}{y} = \\frac{4}{2}\\), so \\(w = 2y\\) and \\(A(y) = 10\\cdot 2y = 20y\\). The same \\(w\\) is the strip width for force on a triangular plate.',
    when: 'Trough or tank whose ends are triangles; triangular plate.',
    steps: [
      ['Write what you know: \\(b\\) = width of the wide edge, \\(h\\) = height, \\(\\ell\\) = length. Which way does the point face?', 'Using \\(b\\) for every slice.'],
      ['The equation it gives (similar triangles) with your numbers.', 'Flipping the fraction: width goes with width.'],
      ['Solve for \\(w\\), then \\(A(y) = \\ell\\cdot w\\).', 'Forgetting to multiply by the length.'],
    ],
    check: '\\(w = 0\\) at the point, \\(w = b\\) at the wide edge.',
  },
  {
    id: 'sh-trap', sec: 'Shapes', title: 'Trough: trapezoid ends', types: ['sh-trap'],
    formula: 'Origin at the middle of the bottom edge. The width changes in a straight line from \\(b_1\\) (bottom) to \\(b_2\\) (top): $$w = b_1 + \\frac{b_2 - b_1}{h}\\,y,\\qquad A(y) = \\ell\\cdot w$$ Example: \\(b_1 = 2\\), \\(b_2 = 6\\), \\(h = 4\\), \\(\\ell = 10\\): \\(w = 2 + \\frac{6 - 2}{4}y = 2 + y\\), \\(A(y) = 10(2 + y) = 20 + 10y\\).',
    when: 'Trough, dam face or plate shaped like a trapezoid.',
    steps: [
      ['Write what you know: bottom width \\(b_1\\), top width \\(b_2\\), height \\(h\\), length \\(\\ell\\).', 'Swapping top and bottom.'],
      ['The equation it gives: start at \\(b_1\\), add \\(\\frac{b_2 - b_1}{h}\\) per unit of height.', 'Using \\(\\frac{b_2}{h}\\) (that is a triangle).'],
      ['Check the top: \\(w(h) = b_2\\). Then \\(A(y) = \\ell\\cdot w\\).', 'Not checking.'],
    ],
    check: '\\(w(0) = b_1\\) and \\(w(h) = b_2\\).',
  },
  {
    id: 'sh-semi', sec: 'Shapes', title: 'Trough: semicircle ends', types: ['sh-semi'],
    formula: 'The slice is a rectangle, \\(\\ell\\) long and \\(2x\\) wide. Flat side up, origin at the centre of the top edge (bottom at \\(y = -R\\)): $$x^2 + y^2 = R^2\\;\\Rightarrow\\; x = \\sqrt{R^2 - y^2},\\qquad A(y) = 2\\ell\\sqrt{R^2 - y^2}$$ Origin at the lowest point (centre at \\(y = R\\)): \\(x = \\sqrt{R^2 - (y - R)^2}\\). Example: \\(R = 2\\), \\(\\ell = 10\\), origin at the top centre: \\(A(y) = 20\\sqrt{4 - y^2}\\) for \\(-2 \\le y \\le 0\\).',
    when: 'Trough with semicircular ends; semicircular plate.',
    steps: [
      ['Write what you know: \\(R\\), \\(\\ell\\), where the origin is, so where the centre is.', 'Putting the centre at the bottom.'],
      ['The equation it gives (Pythagoras) with the shift if the centre is not at \\(y = 0\\).', 'Forgetting the shift \\(y - R\\).'],
      ['Solve for the half-width \\(x\\); \\(A(y) = \\ell\\cdot 2x\\).', 'Using \\(x\\) as the full width, or \\(\\pi r^2\\) (the slice is not a circle).'],
    ],
    check: 'Widest (\\(2R\\)) at the flat top, 0 at the bottom.',
  },
  {
    id: 'sh-para', sec: 'Shapes', title: 'Trough: parabola ends', types: ['sh-para'],
    formula: 'Origin at the vertex, edge \\(y = ax^2\\). $$x = \\sqrt{\\frac{y}{a}},\\qquad A(y) = \\ell\\cdot 2x = 2\\ell\\sqrt{\\frac{y}{a}}$$ Given the top width \\(b\\) and height \\(h\\) instead: \\(h = a\\left(\\frac{b}{2}\\right)^2\\) gives \\(a\\). Example: \\(y = x^2\\), \\(\\ell = 5\\): \\(x = \\sqrt{y}\\), \\(A(y) = 10\\sqrt{y}\\).',
    when: 'Trough or plate whose edge is a parabola.',
    steps: [
      ['Write what you know: the parabola (or top width and height, then find \\(a\\)), and \\(\\ell\\).', 'Using the full top width \\(b\\) as \\(x\\) (the corner is at \\(\\frac{b}{2}\\)).'],
      ['The equation it gives: \\(y = ax^2\\) at the edge.', 'Multiplying by \\(a\\) instead of dividing.'],
      ['Solve for \\(x\\), then \\(A(y) = \\ell\\cdot 2x\\).', 'Forgetting the 2: \\(x\\) is half the width.'],
    ],
    check: '\\(x = 0\\) at the vertex; at the top \\(2x\\) equals the top width.',
  },
];
